#cloud-config
users:
  - name: vagrant
    groups: sudo
    shell: /bin/bash
    sudo: 'ALL=(ALL) NOPASSWD:ALL'
    ssh-authorized-keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAAEAQC/ni0B8ve8/iGVSnAMD6jcpxBVM6poqB2C5Z507SucmJH206XKlR+eMMsGnYGZxBiFDW2uAob6zSZVu51PtpwkFH27tMFnU4YeLD+DB45euWJDuQggNNJIBChxsR7UGvU7aLIAFymzuX8nAJlZiYgMBt9nddu0B1RvTzNZu08rJ95BnQxFEFjN0OvJJ5NguAYf3IFb8jHzxogpOlUwh4upMAxBuSYf7M+G6C4/MnF9ZhlAcpMwl9og03GO0vTsrVfZWJbwKsJYzFlcvfMcp7PDIMJLsgq93Db0R6Wr+2RZgUioWYgEjHEX7I+oMpdjw/2Rc5esvf42hCLCqXGmlFLc9aDkLbW7p/C0dkT/9vVg05JfaMM1COJiLw1BeA7s3BdhF2BU+j5AcjQd/W+pgSOoP/jq3uRMOd0VnZDWMRQi8j9DLE5jCDfc8Q86brN291zJooyg9EH1qCJwI/NBtMIzjFeosIzifyJ1qg9h4+Hs+ZVkrE/87ujGzAgylk1CwFgdIpv3O4iSNDt/7ogX1+dFUZryQys9Ce30RPDWeP+ngp2EX0Ge3O9xcCfQkwD5GDFJmQNSDLM3GUSNUvG/HXj3/jN9+mtOuhWdGD3RLSUuput47YvmFBRgLvYmoSfx1UuXOoXpRd9Dne1nUIcHDDOhMuwA1RB1ds1iHpvz6+b3i8S1+Ck4sj8bzw+PS9nXmBbbKWeTAIF/A/AYYwiLBsRFk9fifKHaQuSBUbk4QvtjuG1aLgDU/P37GkPZQVX72sefoIFpfQowmeRGE+ipiAKFHOIAle5fwojcnt9ClPV22FLJK/6hG9F8JqO702BxLhFSEZUp37lrPjJYD3HqSDF3TJbE3+TdFm5+G52lEOwyK5hH9UX6RmCtsryIiJOqVRqjW33NBfK7G2IqBujFZ7/ljHe55L9WZSwb02s2XeZmQ9CbJaa+7/0/ADSMVrflwhbypiBZ4XYN15OUBYyzgXfSxbIhm61oF8zbKKY5rnc2zCI12HwRXrjr5qfcxwhMLU150/mV7lb9CtEM9csh+8iVK5w4z7hUo8gucBxs1xUrtf3eA/DEZ5b+VAiwv/oLw8TLDVAnnSma7/kLmJgIJUBGy+bBcIIQtyC80XaLLQKy40Q4h8Ms7gtEEjXIFukwtWC7yBSNAF2lhS8b32VpNPIRUMAA+2IzLgarW541pOqM+EbVCCEl4BMw4xf6R9Va/p0S8DAs0uj+jFR+cL4v/8JrjRHJM6VJSoHS5bmafz62vTyuozNVqU5CxLvORdm5e1Ofs6kgH21VY+L2FLqz8SxpnwgTtqJJ2ZA9TMmZHtC1P6+OUdbCSPqWAYsK6OhtQEj1lkauYvooTdzToglO3IFr
chpasswd:
  list: |
    vagrant:linux
  expire: False
package_upgrade: true
packages:
   - qemu-guest-agent